version: "3"
#*********************************************************************
# integration level test agents                                      *
#*********************************************************************

services:
  #*******************************************************************
  # acapy_pickup: acapy agent loaded with pickup plugin              *
  # for testing                                                      *
  #*******************************************************************

  acapy_pickup:
    image: acapy-plugin-pickup
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      ACAPY_TOOLBOX_LOG_LEVEL: DEBUG
      REDIS_ENDPOINT: redis://redis:6379
    ports:
      - "3001:3001"
    command: >
      start -it http 0.0.0.0 3000 -it ws 0.0.0.0 3002
        --plugin-config-value pickup.persistence=redis
        --plugin-config-value pickup.redis.ttl_hours=168 
        --plugin-config-value pickup.redis.server=redis://redis:6379/0
        -ot http
        -e http://acapy_pickup:3000
        --admin 0.0.0.0 3001 --admin-insecure-mode
        --plugin acapy_plugin_pickup
        --no-ledger
        --log-level debug
        --wallet-type indy
        --wallet-name test
        --wallet-key test
        --auto-provision
        --open-mediation

  echo:
    # Image with session support, replace with latest after merged
    image: ghcr.io/indicio-tech/echo-agent:0.2.0
    ports:
      - "3002:3002"
    command: --host 0.0.0.0 --port 3002 --log-level debug

  redis:
    image: "redis:alpine"

    ports:
     - "6379:6379"

    volumes:
      - ./redis-data:/var/lib/redis
      - ./redis.conf:/etc/redis/redis.conf

    environment:
     - REDIS_REPLICATION_MODE=master

    healthcheck:
      test: nc -z localhost 6379 || exit -1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  #*******************************************************************
  # tester: drives tests for acapy_plugin_pickup in a                *
  # "Juggernaut" fashion!                                            *
  #*******************************************************************

  tests:
    container_name: juggernaut
    build:
      context: .
      dockerfile: ./Dockerfile.test.runner
    environment:
      - WAIT_BEFORE_HOSTS=3
      - WAIT_HOSTS=acapy_pickup:3000,echo:3002
      - WAIT_HOSTS_TIMEOUT=60
      - WAIT_SLEEP_INTERVAL=1
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - AGENT_ENDPOINT=http://acapy_pickup:3000
      - ADMIN_ENDPOINT=http://acapy_pickup:3001
      - WS_ENDPOINT=http://acapy_pickup:3002
      - ECHO_ENDPOINT=http://echo:3002
    depends_on:
      - acapy_pickup
      - echo
      - redis
