version: "3"
services:

  tunnel:
    image: dbluhm/agent-tunnel
    command: -s reverse-proxy:80 -p 4040 -h ${AGENT_TUNNEL_HOST}
    ports:
      - 4040:4040
    depends_on:
      - reverse-proxy

  agent:
    image: acapy-pickup-mediator
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./acapy-endpoint.sh:/acapy-endpoint.sh:ro,z
    environment:
      TUNNEL_ENDPOINT: http://tunnel:4040
    entrypoint: >
      /bin/sh -c '/acapy-endpoint.sh aca-py "$$@"' --
    command: >
      start --arg-file default.yml
        --plugin-config-value pickup.persistence=redis
        --plugin-config-value pickup.ttl=168 
        --plugin-config-value pickup.redis_server=redis://localhost:6379/0
        --log-level DEBUG
    depends_on:
      redis:
        condition: service_healthy
  
  reverse-proxy:
    image: nginx:alpine
    restart: unless-stopped
    environment:
      AGENT_HTTP: "http://agent:3000"
      AGENT_WS: "http://agent:3002"
    ports:
      - 80:80
    volumes:
      - ./mediator.conf.template:/etc/nginx/templates/default.conf.template:z
    depends_on:
      - agent

  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"
    volumes:
      - ./redis-data:/var/lib/redis
      - ./redis.conf:/etc/redis/redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master
    healthcheck:
      test: nc -z localhost 6379 || exit -1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s