version: "3"
services:

  redis:
    image: "redis:alpine"

    ports:
     - "6379:6379"

    environment:
     - REDIS_REPLICATION_MODE=master

    healthcheck:
      test: nc -z localhost 6379 || exit -1
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  #*******************************************************************
  # tester: drives tests for acapy_plugin_pickup in a                *
  # "Juggernaut" fashion!                                            *
  #*******************************************************************

  tests:
    container_name: juggernaut
    build:
      context: ../..
      dockerfile: int/redis/Dockerfile.test.runner
    environment:
      - REDIS=redis:6379
    depends_on:
      redis:
        condition: service_healthy
