# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Code Quality Check

on:
  push:
    branches: [ main ]
  pull_request:

env:
  FLAKE8_VERSION: 6.0.0
  BLACK_VERSION: 23.3.0

jobs:
  format:
    name: Format and Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        id: setup
        uses: actions/setup-python@v5
        with:
            python-version: '3.10'
            cache: 'pip'
            cache-dependency-path: '.github/workflows/requirements.cqc.txt'
      - name: Install dependencies
        run: pip install -r .github/workflows/requirements.cqc.txt
      - name: Black Format Check
        run: python -m black --check acapy_plugin_pickup tests int/tests
      - name: Lint with flake8
        run: |
          python -m flake8 . --exclude=env --count --select=E9,F63,F7,F82 --show-source --statistics
          python -m flake8 . --exclude=env --count --exit-zero --max-complexity=10 --max-line-length=90 --statistics
