name: Upload Package

on:
  release:
    types: [created]

env:
  PYTHON_VERSION: 3.9

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python
        id: setup
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'
      - name: Install dependencies
        if: steps.setup.outputs.cache-hit != 'true'
        run: poetry install
      - name: Confidence check (run tests)
        run: poetry run pytest tests
      - name: Build package
        run: poetry build
      - name: Publish package
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{secrets.pypi_upload}}
        run: poetry publish
